# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('Mobile', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='手机号')),
                ('JiFen', models.CharField(max_length=16, verbose_name='积分')),
                ('KuaiDian', models.CharField(max_length=16, verbose_name='快点')),
                ('YuE', models.CharField(max_length=19, verbose_name='余额')),
                ('DongJie', models.CharField(default='0', max_length=2, verbose_name='冻结')),
            ],
        ),
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('Idc', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('Mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('RealName', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('IdcFront', models.ImageField(upload_to='upload_imgs', verbose_name='照片正面')),
                ('IdcBack', models.ImageField(upload_to='upload_imgs', verbose_name='照片背面')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Mobile', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='手机号')),
                ('AltUserName', models.CharField(max_length=100, verbose_name='马甲号')),
                ('Platform', models.CharField(max_length=10, verbose_name='平台')),
                ('Level', models.CharField(max_length=2, verbose_name='账号级别')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromUser', models.CharField(max_length=100, verbose_name='转出方')),
                ('ToUser', models.CharField(max_length=100, verbose_name='转入方')),
                ('ModifiTime', models.DateTimeField(verbose_name='修改时间')),
                ('TransType', models.CharField(max_length=2, verbose_name='交易类型')),
                ('MoneyType', models.CharField(max_length=2, verbose_name='资金类型')),
                ('Quntity', models.CharField(max_length=16, verbose_name='金额')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserName', models.CharField(max_length=100, verbose_name='用户名')),
                ('PassWord', models.CharField(max_length=64, verbose_name='密码')),
                ('Mail', models.CharField(max_length=64, verbose_name='邮箱')),
                ('VerifiedMail', models.CharField(default=0, max_length=1, verbose_name='邮箱是否认证')),
                ('QQ', models.CharField(max_length=16, verbose_name='qq号')),
                ('WeChat', models.CharField(max_length=100, verbose_name='微信账号')),
                ('Mobile', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='手机号')),
                ('Status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('RefUserID', models.CharField(max_length=20, verbose_name='推荐人ID')),
                ('Level', models.CharField(default='0', max_length=2, verbose_name='用户等级')),
                ('VerifiedViedo', models.CharField(default='0', max_length=2, verbose_name='视频认证')),
                ('Type', models.CharField(default='0', max_length=2, verbose_name='用户类型')),
            ],
        ),
    ]
